run:
  tests: false
  skip-dirs:
    - vendor
  skip-files:
    - \.pb\.go$
    - \.pb\.validate\.go$
    - \.pb\.gw\.go$

linters-settings:
  dupl:
    threshold: 500
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/golangci/golangci-lint)
  lll:
    line-length: 160

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errorlint
    - forcetypeassert
    - gocognit
    - goconst
    - gocyclo
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - makezero
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - paralleltest
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - tenv
    - testpackage
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
    - text: "File is not `goimports`-ed with -local github.com/golangci/golangci-lint"
      linters:
        - goimports