run:
  tests: false
  skip-files:
    - \.pb\.go$
    - \.pb\.validate\.go$
    - \.pb\.gw\.go$

linters-settings:
  dupl:
    threshold: 500
  gci:
    local-prefixes: github.com/golangci/golangci-lint
  lll:
    line-length: 160

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errorlint
    - forcetypeassert
    - gocognit
    - goconst
    - gocyclo
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - makezero
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - paralleltest
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - tenv
    - testpackage
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - copyloopvar # Замена exportloopref


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
    - text: "File is not goimports-ed with -local github.com/golangci/golangci-lint"
      linters:
        - goimports

