 linters:
     enable:
       - gofmt
       - golint
       - errcheck
       - staticcheck
       - unused

   issues:
     exclude-rules:
       - path: _test\.go
         text: "should not use ..."

   run:
     timeout: 5m